.md generator
kysect/AssignmentReporter pull request #12
Opened 2021-06-03 20:12 UTC by ronimizy

2021-06-03 20:42 UTC, Bibletoon requested changes

2021-06-03 20:42 UTC, Bibletoon commented on Kysect.AssignmentReporter.Polygon/Program.cs
> +            string path = @"/Users/george/Documents/Programming2Sem/Lab1/";
Как это сюда попало?

2021-06-03 20:42 UTC, Bibletoon commented on Kysect.AssignmentReporter.Polygon/Program.cs
> +            var source = new FileContainer("source.md", path, "");
Мб сделать конструктор с двумя параметрами, или хотя бы передавать String.Empty

2021-06-03 20:42 UTC, Bibletoon commented on Kysect.AssignmentReporter/Models/DirectorySearchFilter.cs
> +        public string RegularExpression { get; set; } = "";
String.Empty вместо пустых кавычек

2021-06-03 20:42 UTC, Bibletoon commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        public string RegularExpression { get; set; } = "";
String.Empty вместо пустых кавычек

2021-06-03 20:42 UTC, Bibletoon commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        public FileSearchFilter(List<string> unacceptableExtensions, List<string> unacceptableNames)
А что за рандомный шарподок (хз как называется правильно)?

2021-06-03 20:42 UTC, Bibletoon commented on Kysect.AssignmentReporter/ReportGenerator/MarkdownReportGenerator.cs
> +                builder.Append("\n");
Зумеры не смогли изобрести AppendLine

2021-06-03 20:42 UTC, Bibletoon commented on Kysect.AssignmentReporter/ReportGenerator/ReportGeneratorExtensions.cs
> +                var report = new FileContainer(fileGroup.Key, destination.Directory, "");
String.Empty вместо пустых кавычек

2021-06-03 20:48 UTC, I-SER-I commented on Kysect.AssignmentReporter/ReportGenerator/MarkdownReportGenerator.cs
> +                builder.Append("\n");
Токс

2021-06-03 20:48 UTC, ronimizy commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        public FileSearchFilter(List<string> unacceptableExtensions, List<string> unacceptableNames)
Экстеншены могут быть с точкой и без, тут явно указано что ожидаются экстеншены с точкой

2021-06-03 21:43 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/FileSystemSourceCodeProvider.cs
> +                    new FileContainer(info.Name, info.DirectoryName, File.ReadAllText(info.FullName))).ToList();
Переносы строк сделай для читаемости

2021-06-04 05:56 UTC, annchous commented
Почему ишую не прикрепил?(

2021-06-04 07:26 UTC, FrediKats requested changes

2021-06-04 07:26 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/DirectorySearchFilter.cs
> +            return descriptor.Directory.Split('\\', '/')
У Path есть сепаратор, он сам определяет по системе.

2021-06-04 07:26 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/DirectorySearchFilter.cs
> +                .ToList().Count == 0;
Возможно стоит выделить интерфейс и разделить на две реализации, чтобы не думать что делать, когда эти штуки пересекаются.

2021-06-04 07:26 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileDescriptor.cs
> +            Extension = Path.GetExtension(name);
Мне кажется, что проще всего тут заюзать FileInfo

2021-06-04 07:26 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/IReportGenerator.cs
> +        FileContainer Generate(FileDescriptor result, List<FileContainer> files,
Туду можно убрать.

2021-06-04 07:26 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/MarkdownReportGenerator.cs
> +        };
Лучше вынести в отдельный класс.

2021-06-04 07:26 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/MarkdownReportGenerator.cs
> +                string extension = file.Extension.Remove(0, 1);
Лучше жкстеншен без точки просто хранить.

2021-06-04 07:26 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +                new BasicAuthentication(new SecretStore("git")).GetCredentials(new TargetUri("https://github.com"));
Я думаю стоит отключить автоврап.

2021-06-04 09:53 UTC, ronimizy commented on Kysect.AssignmentReporter/Models/DirectorySearchFilter.cs
> +            return descriptor.Directory.Split('\\', '/')
done

2021-06-04 11:57 UTC, ronimizy commented on Kysect.AssignmentReporter/Models/FileDescriptor.cs
> +            Extension = Path.GetExtension(name);
done

2021-06-04 11:57 UTC, ronimizy commented on Kysect.AssignmentReporter/ReportGenerator/IReportGenerator.cs
> +        FileContainer Generate(FileDescriptor result, List<FileContainer> files,
done

2021-06-05 13:45 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/MarkdownReportGenerator.cs
> +        };
Обсудили. Не нужно.

2021-06-05 13:46 UTC, FrediKats approved these changes

2021-06-05 15:53 UTC, merged