feat/SearchFilters
kysect/AssignmentReporter pull request #13
Opened 2021-06-05 15:51 UTC by TomGnill

2021-06-05 15:52 UTC, TomGnill commented
Насчёт CheckFormat() не оч уверен что хорошая идея, но так можно предохраняться от двойных форматов по типу xaml.cs

2021-06-05 16:07 UTC, ronimizy requested changes
В такой реализации нет смысла разбивать фильтр файлов и директорий, так как списки держат критерии для одного и другого. Вижу такие варианты:
1) Разбить списки на списки для путей и файлов
2) Сделать один фильтр

Хочу услышать мнение @FrediKats  про то, стоит ли делать конструкторы фильтров с регулярками

2021-06-05 16:07 UTC, ronimizy commented on Kysect.AssignmentReporter/Models/DirectorySearchMask.cs
> +        }
Стоит добавить пустой конструктор

2021-06-05 16:07 UTC, ronimizy commented on Kysect.AssignmentReporter/Models/FileLists/BlackList.cs
> +            Directory = directories;
Directory -> Directories

2021-06-05 16:07 UTC, ronimizy commented on Kysect.AssignmentReporter/Models/FileLists/BlackList.cs
> +        }
+ добавить частичные конструкторы

2021-06-05 16:07 UTC, ronimizy commented on Kysect.AssignmentReporter/Models/FileLists/WhiteList.cs
> +            Directory = directories;
То же по неймингу

2021-06-05 16:07 UTC, ronimizy commented on Kysect.AssignmentReporter/Models/FileLists/WhiteList.cs
> +        }
То же по конструкторам

2021-06-05 16:07 UTC, ronimizy commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        }
То же по пустому конструктору

2021-06-05 16:17 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileLists/BlackList.cs
> +        }
ты же понимаешь что когда у меня 3 поля одного типа это не сработает)

2021-06-05 16:17 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        }
сделано так, что ты просто null передаёшь. если тебе фильтр не нужен

2021-06-05 16:21 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        }
хотя если ты планируешь везде json юзать, я тогда во всех классах сделаю пустые конструкторы, но я не знал что такая необходимость есть)

2021-06-05 16:54 UTC, annchous commented on Kysect.AssignmentReporter/Models/DirectorySearchMask.cs
> +            bool whiteListAllowed = true;
Флаги @_@

2021-06-05 17:02 UTC, annchous commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
>          }
Метод с названием `CheckFormat` возвращает строку... как-то странно. И вообще, если ты хочешь получить всё после первой точки, то это можно сделать гораздо короче.

2021-06-05 17:07 UTC, annchous commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        }
:/

2021-06-05 18:11 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
>          }
> Метод с названием `CheckFormat` возвращает строку... как-то странно. И вообще, если ты хочешь получить всё после первой точки, то это можно сделать гораздо короче.

скажи как

2021-06-05 18:37 UTC, annchous commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
>          }
Ну например
```csharp
fileName.Substring(fileName.IndexOf("."))
```

2021-06-05 20:16 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
>          }
> Ну например
> 
> ```cs
> fileName.Substring(fileName.IndexOf("."))
> ```

спасибо, вставил проверку на наличие точки и работает как часы

2021-06-06 11:01 UTC, annchous commented on Kysect.AssignmentReporter.Polygon/Program.cs
> +            ISourceCodeProvider sourceCodeProvider = new FileSystemSourceCodeProvider(@"C:\Users\andri\source\repos\ITMO_OOP_2020", fileSearchFilter);
Путь

2021-06-06 11:01 UTC, annchous commented on Kysect.AssignmentReporter.Polygon/Program.cs
> +            WhiteList wl = new WhiteList(null, new List<string>() { ".cs" }, null);
Нейминг

2021-06-06 11:06 UTC, TomGnill commented on Kysect.AssignmentReporter.Polygon/Program.cs
> +            ISourceCodeProvider sourceCodeProvider = new FileSystemSourceCodeProvider(@"C:\Users\andri\source\repos\ITMO_OOP_2020", fileSearchFilter);
да я просто тестил как работает и оставил пример, что вы начинаете то сразу

2021-06-06 11:07 UTC, TomGnill commented on Kysect.AssignmentReporter.Polygon/Program.cs
> +            WhiteList wl = new WhiteList(null, new List<string>() { ".cs" }, null);
ответил выше

2021-06-06 13:34 UTC, ronimizy commented on Kysect.AssignmentReporter/Models/FileLists/BlackList.cs
> +            return false;
Вспоминаются мамы про индусов

2021-06-06 14:30 UTC, ronimizy approved these changes

2021-06-06 15:10 UTC, merged

2021-06-07 13:16 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
>          }
> Ну например
> 
> ```cs
> fileName.Substring(fileName.IndexOf("."))
> ```

@annchous Да когда ты уже станешь человеком и начнешь слайсить!

2021-06-07 13:32 UTC, hrrrrustic commented
@FrediKats, @s4xack 
Чисто уточнить, не подумайте, что я токсик
Но что здесь вообще происходит?
Почему @ronimizy Сам что-то написал, сам заапрувил и сам смержил?
В 10 раз повторение про хардкор путей не убрано, часть реквестов от @annchous не исправлено, выше вброс про мемы от индусов не убраны. С реквест чейнжесом по частичным конструкторам абсолютно не согласен.
Часть изначального кода от @TomGnill удалена и переписана под свой же реквест чейнжс.

2021-06-07 13:38 UTC, hrrrrustic commented on Kysect.AssignmentReporter.Polygon/Program.cs
> +            ISourceCodeProvider sourceCodeProvider = new FileSystemSourceCodeProvider(@"C:\Users\andri\source\repos\ITMO_OOP_2020", fileSearchFilter);
Я вот потестил и оставил путь до экзешника с rm -rf от корня фс. Удачной разработки!

2021-06-07 13:40 UTC, hrrrrustic commented on Kysect.AssignmentReporter.Polygon/Program.cs
> +            ISourceCodeProvider sourceCodeProvider = new FileSystemSourceCodeProvider(@"C:\Users\andri\source\repos\ITMO_OOP_2020", fileSearchFilter);
Не нужно рассматривать каждый комментарий как "фу у тебя тут гавной воняет убери". Это ок, что локальные штуки просачиваются - тебе просто напомнили, что ты случайно залил это и надо убрать

2021-06-07 13:40 UTC, FrediKats commented
Я солидарен с поинтом, что тут явно что-то пошло не по плану.

2021-06-07 14:04 UTC, hrrrrustic commented
Ну, солидарность это конечно круто, но этот разговор уже не новый. Кроме солидарности пока ничего больше и не видел.

2021-06-07 16:01 UTC, ronimizy commented
@hrrrrustic Если посмотреть на временные отметки то между коммитом и мержем прошло 40 минут, за это время @TomGnill посмотрел мои доработки его реализации и подтвердил их (если надо могу скринами в дискорд пруфануть). Так как замечания, кроме как про наличие прямого пути в коде, были исправлены, решил сразу замержить. Надо было подождать и зареквестить у кого-нибудь ревью, больше так делать не буду.
Если есть конкретные претензии по коду - оформи ишую, всё поправлю.

2021-06-07 16:11 UTC, TomGnill commented
Мы уже эту тему обсудили, что никто свой код больше в мои реквесты не пишет, у нас просто в начале не совсем сложилось с взаимопониманием

2021-06-07 17:08 UTC, hrrrrustic commented
>Если посмотреть на временные отметки

Мне нужно тратить на это время, созваниваться с космосом, расшифровывать послания, читать ваши мысли. Сомневаюсь, что у кого-то будет желание заниматься этим.

>в дискорд пруфануть

Мне не нужны никакие пруфы, мне не надо что-то доказывать. Я здесь не чтобы сказать, что "ну капец вы, как так можно вообще, щяс я вам покажу как надо и вообще вас захейчу!!11" . Просто если вы решаете что-то там между собой, то так и напишите перед мержем, чтобы вообще хоть как-то можно было понять, что тут произошло.

>кроме как про

Этого достаточно для того, чтобы НЕ мержить

>и зареквестить у кого-нибудь ревью

Ну, это да. Тут просто больше проблема не в том, что заревьюил только ты. А в том, что ты участвовал в написании этого кода => автоматом снижается твой вес в плане апрува.

>больше так делать не буду

Ты можешь мержить, но просто делать это не надо не после первого же апрува от кого-то. Насколько я знаю, можно настроить минимальное кол-во аппрувов и немного подшаманить с весомостью аппрува от конкретных людей, но @FrediKats как бог уворачивается от этой темы.

>оформи ишую

tbh мне лень это делать. В пр'е это сделать намного проще и быстрее, а щас мне надо лезть куда в сурсы, бегать ctrl+f искать реализации, смотреть кучу файлов наугад и вот это все

>код больше в мои реквесты не пишет

Неплохо было бы. Если прям очч хочется, то тоже можно бы написать какой-нибудь комментарий по типу "автор умер", чтобы это не выглядело как будто ты просто пришел и такой, ну чет автор лох, написал говно какое-то, ща перепишу

>не совсем сложилось с взаимопониманием

Верю в вас!