Feat/docx,pdf gen
kysect/AssignmentReporter pull request #17
Opened 2021-06-16 23:04 UTC by TomGnill

2021-06-17 05:41 UTC, FrediKats requested changes

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileLists/BlackList.cs
> +            bool fileIsAllowed = FileNames?.Contains(fileName) ?? true;
Проверяй на null в конструкторе. Если передали null, то сразу лучше ошибку бросать - это не ок. Ну и сеттер убрать.

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileLists/BlackList.cs
> +            bool fileIsAllowed = FileNames?.Contains(fileName) ?? true;
.Contains(fileName) - это не оч т.к. нельзя, например,  сделать IgnoreCase

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileLists/BlackList.cs
> +            return false;
Я даже не буду это комментировать.

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileDescriptor.cs
> +        public string Directory { get; set; }
Лушче указать, что это RootDirectory

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileDescriptor.cs
> +        public FileDescriptor(string name,string content, string directory)
Форматирование =_=

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileLists/BlackList.cs
> +        public bool FormatIsNotAcceptable(string fileFormat)
Отступы =_=

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileLists/WhiteList.cs
> +    public class WhiteList
Я уже писал и мне все еще не нравится что у нас два около одинаковых класса - BlackList и WhiteList

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            bool blackListAllowed = BlackList?.FileIsNotAcceptable(fileName) ?? true;
Аналогично - проверяй все в конструкторе, убирай сеттеры. Поддерживай инвариант.

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            return blackListAllowed & whiteListAllowed;
А почему &?..

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        }
Нарушение инкапсуляции, на ООП я бы за такое баллы бы снимал.

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        }
Такое лучше не делать руками. Как минимум, сломается на файлах, где в имени точки есть. Лучше использовать FileInfo, у него есть нужное поле (ты кста его удалял как раз с FileDescriptor'а)

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/TitlePageInfo.cs
> +        public string TeacherName { get; set; } = string.Empty;
Втыкивание пустых строк выглядит ниоч. А почему это не null? И вообще, кажется, что тут всегда значения должны быть.

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/TitlePageInfo.cs
> +        }
Я уже писал про отступы, надеюсь ты по всему PR посмотришь.

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/TitlePageInfo.cs
> +        public string WorkNumber { get; set; } = string.Empty;
Название не очень.

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            par[6]
Магические числа.

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +        public TitlePageInfo titlePage;
Кодстайл.

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            else
Что? Почему?

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +                }
А почему это происходит не в методе ?

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +                for (int i = 0; i < 22; i++)
Магические числа

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            return new FileDescriptor(documentInfo.Name, string.Empty, documentInfo.DirectoryName);
А почему тут string.Empty?

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +                .FontSize(15)
Вынеси в отдельный метод логику заполнения файла. А то тут чет очень уж непонятный метод, который делает все.

2021-06-17 05:41 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/MarkdownReportGenerator.cs
> -                builder.AppendLine(extension);
Это же не будет работать. Ты просто сломал код, который тут был, разве нет?

2021-06-17 07:15 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/MarkdownReportGenerator.cs
> -                builder.AppendLine(extension);
там просто съехал первый '''

2021-06-17 07:16 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/TitlePageInfo.cs
> +        public string TeacherName { get; set; } = string.Empty;
ну я же могу передать и заполненный титульник, и мне не придётся указывать все эти поля

2021-06-17 07:17 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/TitlePageInfo.cs
> +        }
да  я смотрю, там просто реально кучу всего надо было переделывать, я за всем не мог уследить)

2021-06-17 07:24 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/TitlePageInfo.cs
> +        }
Именно поэтому я и говорю каждый раз, чтобы ты делал небольшие изменения...

2021-06-17 07:27 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/MarkdownReportGenerator.cs
> -                builder.AppendLine(extension);
Не понял. До твоих изменений писался ```extension, сейчас не пишется extension.

2021-06-17 07:27 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/TitlePageInfo.cs
> +        }
Спам коммитов не оч хорошо

2021-06-17 21:24 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileLists/BlackList.cs
> +            bool fileIsAllowed = FileNames?.Contains(fileName) ?? true;
зная ка это используется, тут null просто не может быть)

2021-06-17 21:50 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        }
тут честно хз как сделать лучше.

2021-06-17 21:51 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            par[6]
так проще, думаю парсить документ это будет отдельная заноза, тем более раз уж у нас шаблон один, то можно и воспользоваться этим

2021-06-17 21:52 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            else
попытка обойти защиту

2021-06-17 22:03 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +                for (int i = 0; i < 22; i++)
Секрет фирмы

2021-06-17 22:03 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            return new FileDescriptor(documentInfo.Name, string.Empty, documentInfo.DirectoryName);
Ну я могу вернуть содержимое документа, но это плохая идея

2021-06-17 22:17 UTC, TomGnill commented
1. Стадии генерации вынес в отдельные методы.
2. На конвертировании в PDF пока оставлю заглушку, буду пробовать через OpenXML что-то сделать
3. Black/White листы смерджил в что-то менее кринджовое. Но тут проблема что я не могу сделать конструктор в который передам что-то из.
4. Отрефакторил логику где это было видно, в моменте с проверкой директории не очень понимаю что можно придумать интересного.
5. Теперь передаём на проверку FileInfo, я просто не замечал что там есть поле Extention, поэтому и собственно херню сделал.
6. С .md вроде проблема решена, генерируется тоже самое что и раньше.
7. Ну и по мелочи. Убрал лишние пробелы, отступы где заметил, некоторые сущности переименованы.

2021-06-18 05:51 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        }
У тебя есть WhiteList. Тебе не важно что и как он делает внутри. Я ожидаю, что у него будет один паблик метод, который проверит и вернет true или false. Все остальное - детали реализации и должны быть инкапсулированы.

2021-06-18 05:52 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/TitlePageInfo.cs
> +        }
Плохо читаемый код - это не оч хорошо. А чем комиты тебе мешают - для меня загадка.

2021-06-18 06:05 UTC, FrediKats requested changes

2021-06-18 06:05 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/MarkdownReportGenerator.cs
> -                builder.AppendLine(extension);
Проблема все еще есть.

2021-06-18 06:05 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/FileSystemSourceCodeProvider.cs
> +                     && _fileSearchFilter.FileIsAcceptable(info))
Может это тоже имеет смысл инкапсулировать? Есть ли ситуации, когда мы хотим проверять только одно из 3 правил?

2021-06-18 06:05 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            return new FileDescriptor(documentInfo.Name, string.Empty, documentInfo.DirectoryName);
Но возвращать FileDescriptor в котором неправильно указан Content - идея тоже не из лучших. Нарушаешь инвариант. Когда ты вернешь мне FileDescriptor, я буду считать, что он описывает файл. А значит, должен буду поверить, что файл пустой.

2021-06-18 06:05 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            return BlackList?.FileIsNotAcceptable(file.Name) ?? (WhiteList?.FileIsAcceptable(file.Name) ?? true);
Все еще остались null значения, и теперь все методы обрастают проверками на null. Да, сахар позволяет скрывать, но не решает проблему. Мы не можем создавать дефолтный лист вместо null значения?

2021-06-18 06:05 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            WhiteList = null;
Кажется, для таких ситуация и существует паттерн Фабричный метод.

2021-06-18 06:06 UTC, FrediKats commented
А еще, стоит конфликт разрезолвить.

2021-06-18 08:50 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/FileSystemSourceCodeProvider.cs
> +                     && _fileSearchFilter.FileIsAcceptable(info))
Я кстати думал об этом 
Может вообще в отдельный метод вынести всё это?

2021-06-18 08:52 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            return BlackList?.FileIsNotAcceptable(file.Name) ?? (WhiteList?.FileIsAcceptable(file.Name) ?? true);
Ну если ты против не буду сделаю дефолтные листы с игнором гит файлов 
А добавление своего листа будет плюсоваться к дефолтному или заменять его? @FrediKats

2021-06-18 08:52 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            WhiteList = null;
Сделаем

2021-06-18 08:53 UTC, TomGnill commented
ну спасибо что конфликтует только Program.cs

2021-06-18 09:58 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            return BlackList?.FileIsNotAcceptable(file.Name) ?? (WhiteList?.FileIsAcceptable(file.Name) ?? true);
Дак дело не в том, что я против. У тебя код будет дальше обрастать нал чеками и ты в методе либо будешь каждой второй строчкой проверять на null, либо ловить null reference.
А что ты собрался плюсовать? Кажется, тебе нужно либо использовать то, что передал пользователь, либо дефолтный лист.

2021-06-18 16:15 UTC, TomGnill commented
1.Проверка всех фильтров теперь в одном методе.
2.Документ теперь возвращается в виде FileDescriptor, вместе с содержимым
3.

2021-06-18 18:45 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/FileLists/BlackList.cs
> +            bool fileIsAllowed = FileNames?.Contains(fileName) ?? true;
1. У тебя публичный класс, о каких 

> зная как это используется

может идти речь?

2. А че ж у тебя тогда миллиард ? и ?? везде намазано. 

Аргументация ни о чем. Причину отказа от предложенного варианта не понял. Ты попросил уже третье ревью, но самое первое сообщение из первого же ревью все еще на том же месте.

2021-06-18 18:47 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        }
Два реквеста ревью спустя ничего не изменилось.

2021-06-18 18:49 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/TitlePageInfo.cs
> +        public string TeacherName { get; set; } = string.Empty;
Где связь между вопросом и твоим ответом?

2021-06-18 18:50 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/TitlePageInfo.cs
> +        }
>Спам коммитов не оч хорошо

JSON Стетхем (с) ?

Откуда вообще такое утверждение?

2021-06-18 18:51 UTC, hrrrrustic commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            par[6]
Вполне очевидно, что на скрытый вопрос "Какого хрена тут какое-то рандомное число?" ожидается услышать что-то лучше, чем "так проще"

2021-06-18 18:51 UTC, hrrrrustic commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            else
Твой ответ привнес около 0 информации, но зато добавил новых вопросов!

2021-06-18 18:53 UTC, hrrrrustic commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +                for (int i = 0; i < 22; i++)
Все очень рады за твою фирму, но ожидается, что он исчезнет.
Что ты ожидаешь услышать сейчас в новом запрошенном ревью, когда половина старых не исправлена?

2021-06-18 18:55 UTC, hrrrrustic commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +                .FontSize(15)
Я все еще вижу килотонну подряд идущих foreach с каким-то рандомными фонтсайзами, шрифтами и тд. Данный коммент ни Outdated, ни зарезолвлен, ни привлек никакой реакции.

2021-06-18 19:00 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/FileLists/WhiteList.cs
> +    public class WhiteList
Проблема не исправлена.

2021-06-18 19:01 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +                for (int i = 0; i < 22; i++)
> Все очень рады за твою фирму, но ожидается, что он исчезнет.
> Что ты ожидаешь услышать сейчас в новом запрошенном ревью, когда половина старых не исправлена?

Не по фактам, Но если тебе очень интересно что все эти числа значат, то слушай: этот цикл просто делает отступы от информации об отчёте, чтобы в титульнике не висел код, предыдущий комментарий вообще мимо кассы, сейчас конвертация в PDF происходит иначе, касательно рандомных чисел я уже говорил - парсить документ идея не супер хорошая да и места где мы указываем информацию в ШАБЛОНЕ мы знаем заранее.

2021-06-18 19:03 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +                for (int i = 0; i < 22; i++)
Ну и если вы хотите пихать разные титульники, можно было бы об этом сказать, а то ктож знал что шаблонов будет много.

2021-06-18 19:12 UTC, hrrrrustic reviewed
Конфликт не исправлен.
Да, я душнила.
Правильно понимаю, что спам коммитов это не оч, но спам ревью реквестов без исправлений предыдущих это ок?

@FrediKats Ты узнал слово инвариант?)

2021-06-18 19:12 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            new List<string>());
Это выглядит мягко говоря не очень. Что это за куча пустых листов?

2021-06-18 19:12 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            }
Это не решение проблемы. Ты просто сделал общий класс и перенес в них поля. Но твоя логика все еще руками их проверяет на тип и дальше опять идет старое деление на black и white лист

2021-06-18 19:12 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            }
В чем проблема просто сразу сделать 
```C#
xxxAllowed = XXXList?.Directories?.All...
```

2021-06-18 19:12 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/ListOfRules.cs
> +        public ListOfRules() { }
В чем смысл этих конструкторов?
Зачем тут пустой?
Зачем ты в наследниках пишешь точной такой же конструктор с присваиванием тех же полей?

2021-06-18 19:12 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/ListOfRules.cs
> +        }
Ну, во-первых, это лютая копипаста и лапша
Во-вторых, я не понял прикола. Если что-то из этого действительно null, то будет возвращаться `true` на любой запрос.
В-третьих, ты ж сам сказал "Если знать как пользоваться, то null не может быть"! Где та уверенность?

2021-06-18 19:12 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/ReportExtendedInfo.cs
> +    {
Зачем тут пробел?
Тебе только в этом PR уже раза три сказали, следить за форматированием.

2021-06-18 19:12 UTC, hrrrrustic commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            for (int i = 0; i < 22; i++)
Тоже самое число

2021-06-18 19:12 UTC, hrrrrustic commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            return document as DocX;
Ты точно знаешь что делает `as`?

2021-06-18 19:12 UTC, hrrrrustic commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +                        .Replace(".docx", ".pdf"));
Почему метод конвертирования не конвертируют расширение файла?

2021-06-18 19:14 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            new List<string>());
Дефолтные правила. Об этом сказано выше.

2021-06-18 19:15 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            }
Меня чёт уже задолбало кидание от одного к другому, определитесь уже.

2021-06-18 19:15 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            }
Ну я это вот прям только что поменял. Так что тайминг словил.

2021-06-18 19:17 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +                        .Replace(".docx", ".pdf"));
спроси у разработчика либы.

2021-06-18 19:18 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/ReportExtendedInfo.cs
> +    {
Давай так когда мне решарпер вверху пишет ссылки или что-то подобное, то такое не сразу бросается в глаза.

2021-06-18 19:18 UTC, hrrrrustic commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +                for (int i = 0; i < 22; i++)
Лично мне от объяснения не стало ни капли понятнее. Набор несвязных мыслей вслух с горсткой неуместных высказываний про кассу. Предполагается, что ты просто сделаешь это число константой с более-менее несущим смысл названием. 

>можно было бы об этом сказать

То есть ты пишешь код, не зная что вообще нужно написать?
Если это было обговорено, то просто пиши или тудушку или просто коммент в стиле "Пока было решено сделать упрощенную реализацию"

2021-06-18 19:27 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            new List<string>());
Я про то, что тот факт, что среднестатистическое (я так понимаю тут указан реальный пример юзеджа) использование данного функционала требует от меня написать руками создание пачки пустых листов.
Если это работает, то ок, но в целом я бы в будущем все же подумал над улучшением
Я точно до конца не понимаю, что тут происходит, но выглядит как будто можно сделать что-то вроде 
```C#
AccessRules.FromЧтоТо(smth).WithFileNames(smth).WithDirectories(smth)
```
Ну в общем дефолтный билдер

2021-06-18 19:31 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/ReportExtendedInfo.cs
> +    {
Какие ссылки? Что значит не бросается в глаза?
В чем проблема открыть любой git-diff и посмотреть что ты пушишь? На это требуется секунд 20 от силы

Ты понимаешь, что такие вещи гарантированно приводят к тому, что проверяющий человек должен будет как минимум еще один раз прийти и посмотреть заново PR только потому, что ты не захотел проверить свои же изменения?

2021-06-18 19:34 UTC, hrrrrustic commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +                        .Replace(".docx", ".pdf"));
А, это библиотечный метод, тогда окей

2021-06-18 19:35 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +                for (int i = 0; i < 22; i++)
> Лично мне от объяснения не стало ни капли понятнее. Набор несвязных мыслей вслух с горсткой неуместных высказываний про кассу. Предполагается, что ты просто сделаешь это число константой с более-менее несущим смысл названием.
> 
> > можно было бы об этом сказать
> 
> То есть ты пишешь код, не зная что вообще нужно написать?
> Если это было обговорено, то просто пиши или тудушку или просто коммент в стиле "Пока было решено сделать упрощенную реализацию"

Ну вот как раз обговорено что шаблон будет один, о чём ты мог бы и узнать. Константы действительно идея хорошая, будет сделано с ними.

2021-06-18 19:39 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            }
Не знаю о каком кидании идет речь.
Фреди тебе написал, что есть два одинаковых класса - ты переписал логику. Я написал, что переписанная логика не решила эту проблему. Ты все еще в бизнес логике руками делишь эти два класса, чтобы дальше работать с ними по-отдельности.

Можно без токса?
Если цель - просто быстро как угодно собрать работающую версию, то окей, так и напиши.

2021-06-18 19:56 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            new List<string>());
Да я понимаю что три листа это звучит не очень удобно, но если писать отдельные конструкторы то это отдавать предпочтение какому-то одному. За этим есть пустой конструктор в котором можно любой лист сделать как душе угодно. Плюс я знаю что в дальнейшем это будет всё связываться с интерфейсом плагина, поэтому я заранее думаю как сделать так чтобы было +- удобно.

2021-06-18 19:57 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +            }
У нас есть задача, что мы передаём какой-то лист отдельно, и чтобы разобрать передаём мы правила на запрет или на разрешение я сделал два этих класса.

2021-06-18 20:00 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/ReportExtendedInfo.cs
> +    {
Куда тебе закинуть скрин как это выглядит в вижле? Я не понимаю почему тут есть пробел, а у меня его уже коммита как три в коде нет.

2021-06-19 14:53 UTC, FrediKats commented
Сделаю саммари. @TomGnill 

1. Замечание про неудобный конструктор (https://github.com/kysect/AssignmentReporter/pull/17/files#r654639092) . Ты пишешь "но если писать отдельные конструкторы то это отдавать предпочтение какому-то одному", но не так. Тебе предложили решение этой проблемы - сделать билдер.
2. Замечание про листы (https://github.com/kysect/AssignmentReporter/pull/17/files#r654628959). Было предложение  избавится от дублирования классов, но ты просто сделал у них общего предка. В этом коде ты пытался решить проблему того, что нельзя сделать два конструктора с одинаковой сигнатурой, но это очень плохое решение т.к. ломает полиморфизм. Тебе в ревью предлагали сделать это с помощью фабричных методов.
3. "кидание от одного к другому". Я не уверен, что где-то есть примеры противоречивых правок. Тут сложилась ситуация, когда тебе в ревью указывают на проблему и предлагают решение, ты делаешь совершенно другое. Ну и потом получаешь очередные правки на тоже место.
4. Конструктор (https://github.com/kysect/AssignmentReporter/pull/17/files#r654629716) все еще есть, на замечание не ответил, просто нажал резолв.
5. Про пробелы (https://github.com/kysect/AssignmentReporter/pull/17/files#r654652221) несколько раз упоминали. Если в диффе появляются пробелы - значит ты их закомитил. Другого варианта нет. Тебе предложили просто просматривать файлы перед комитов, проверять, что нет лишнего. Это упростит ревью и может спасти от проблем с мерджем. Если же такой пробел попал - можно попробовать следующим комитов его убрать, чтобы в общем диффе его уже не было. Если у тебя его действительно в файле нет, а гит говорит, что есть - это странно. Попробуй code cleanup запустить на файле.
6. Проблема в null (https://github.com/kysect/AssignmentReporter/pull/17#discussion_r653234180) не сказать что решена. Ты просто убрал проверки на null. При этом оставил конструктор, который может создать объект с null полями и он сразу же упадет.
7. Что в этими не нулами (https://github.com/kysect/AssignmentReporter/pull/17#discussion_r653236874) тоже непонятно.
8. Все еще не разрезолвил конфликт.
9. Нейминг комитов не информативный. Потом будет сложно понимать что было сделано в них.

2021-06-20 17:50 UTC, FrediKats requested changes

2021-06-20 17:50 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +        public CoverPageInfo CoverPage;
А почему это паблик поле?

2021-06-20 17:50 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +        public Document WriteInCoverList(CoverPageInfo info, ReportExtendedInfo reportExtendedInfo)
Отсутпы.
Может лучше занейми в LoadAndFillTitlePage? У тебя тут coverList, а внутри PathToTitlePage.

2021-06-20 17:50 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            return (DocX)_document;
А нельзя переменную сделать этого типа?

2021-06-20 17:50 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +        public DocX InsertConclusion(string conclusion)
А эти методы доолжны быть public? Мне казалось, что тут достаточно одного метода-фасада, который все делает.

2021-06-20 17:50 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            }
Кажется, это и есть тот один публичный метод, который будет. Если так, то можно еще этот кусок вынести. Тогда в нем не останется деталей реализации, а будет только описание как по шагам мы генерируем отчет.

2021-06-20 17:50 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchRules/RulesBuilder.cs
> +        public ListOfRules Get()
По канону - Build должен быть)

2021-06-20 17:50 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchRules/ListOfRules.cs
> +    public class ListOfRules
Мне очень не нравится такой нейминг. ListOf - это какой-то очень непонятный для меня способ неймить. Я, кажется, об это тебе говорил на второй лабе по ООП. Можно посмотреть в сторону SearchRule или подобного.

2021-06-20 17:50 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchRules/ListOfRules.cs
> +                           .IsMatch(directory));
Кажется, скобочки лишние
+Не понимаю, почему ты в одном случае делаем Select, а потом Any, а в другом - в методе All сразу создаешь RexExp. Думаю, понятнее было бы, если бы это было консистентно.
+а еще, если строки всегда используются как Regex - может и хранить лист не строк, а Regex?

2021-06-20 17:50 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchRules/IRulesBuilder.cs
> +   public interface IRulesBuilder
В билдере нет метода получения значения.

2021-06-20 17:50 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchRules/FileSearchFilter.cs
> +            }
В шарпах есть оператор ?? для этого. Можно написать
ListOfRules = listOfRules ?? throw new Exception("listOfRules can't be null");

2021-06-20 19:33 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +        public CoverPageInfo CoverPage;
Тут по фактам, я не обратил внимание

2021-06-20 19:36 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            }
Хочешь просто каждый шаг генерации вынести в методы, и в главном методе просто их подряд вызвать?

2021-06-20 19:58 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +            }
В случае, если это единственный паблик метод - да. Тогда можно будет его легко прочитать и понять, что в целом происходит.

2021-06-22 23:23 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchRules/FileSearchFilter.cs
> +            }
не знал что его можно в таком контексте использовать

2021-06-22 23:38 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/DocumentReportGenerator.cs
> +        public Document WriteInCoverList(CoverPageInfo info, ReportExtendedInfo reportExtendedInfo)
Везде сделаю CoverPage.

2021-06-22 23:38 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchRules/RulesBuilder.cs
> +        public ListOfRules Get()
Так. Ресолвить не буду, а то может я не совсем правильно понял что ты имеешь ввиду.

2021-06-22 23:42 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchRules/ListOfRules.cs
> +    public class ListOfRules
SearchSettings сделаю.

2021-06-22 23:54 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchRules/ListOfRules.cs
> +                           .IsMatch(directory));
Я туплю и не помню как мне в regex засунуть массив паттернов и можно ли вообще так делать.

2021-06-22 23:55 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchRules/IRulesBuilder.cs
> +   public interface IRulesBuilder
Я так понимаю ты про Build. Или ты имеешь ввиду получение значений которые мы записали, просто звучит как-то жутко.

2021-06-23 05:07 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchRules/IRulesBuilder.cs
> +   public interface IRulesBuilder
>Я так понимаю ты про Build
Да.

2021-06-23 05:08 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchRules/ListOfRules.cs
> +                           .IsMatch(directory));
Кажется, нельзя. Но я про то, что ты можешь сделать BlackDirectories List<Regex>

2021-06-23 06:37 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchRules/ListOfRules.cs
> +                           .IsMatch(directory));
типа List<Regex>?

2021-06-23 06:37 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchRules/ListOfRules.cs
> +                           .IsMatch(directory));
блин. Стёрлось. лист regex ?

2021-06-23 06:41 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchRules/ListOfRules.cs
> +                           .IsMatch(directory));
Ну да. Ты ж каждый раз проходишь по листу и делаешь из него лист regex. Почему тогда не хранить сразу регулярками?

2021-06-23 11:22 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchRules/ListOfRules.cs
> +                           .IsMatch(directory));
Тогда вроде всё

2021-06-23 13:36 UTC, hrrrrustic commented
> SonarCloud Quality Gate failed.
> 
> [<img alt="Bug" width="16" height="16" src="https://camo.githubusercontent.com/deaad8c9d9b09977da3f9aa455689440a17356bb359560328463022a0d9d1362/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672e706e67">](https://sonarcloud.io/project/issues?id=kysect_AssignmentReporter&pullRequest=17&resolved=false&types=BUG) [<img alt="C" width="16" height="16" src="https://camo.githubusercontent.com/46f32ae0a124fed609facb7b9d8e97c97222c470eb8a1a0b951f5e07ef7f37c4/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f432e706e67">](https://sonarcloud.io/project/issues?id=kysect_AssignmentReporter&pullRequest=17&resolved=false&types=BUG) [1 Bug](https://sonarcloud.io/project/issues?id=kysect_AssignmentReporter&pullRequest=17&resolved=false&types=BUG)

Привет тебе от детей датафлоу анализа кекв
А есть какой-нибудь магический //Resharper disable once для сонара? 🤔 @FrediKats

2021-06-23 13:46 UTC, FrediKats commented
@hrrrrustic Да
![image](https://user-images.githubusercontent.com/22368203/123107820-8d63f380-d442-11eb-8ee3-726053448555.png)

2021-06-26 06:32 UTC, FrediKats commented
Ну класс, Сонар умер.
Здоровья погибшим.

2021-06-26 06:33 UTC, merged