add multiGenerator + SimpleTextGenerator
kysect/AssignmentReporter pull request #19
Opened 2021-07-08 13:13 UTC by TomGnill

Help: как внедрить описание к отчётам?

2021-07-10 08:17 UTC, I-SER-I commented on Kysect.AssignmentReporter/ReportGenerator/SimpleTextReportGenerator.cs
> +            reportFile.Close();
Чет не понял прикола

2021-07-10 17:16 UTC, hrrrrustic commented
_Build FAILED.
13 Warning(s)
 7 Error(s)_

2021-07-10 17:32 UTC, TomGnill commented
Есть вероятность что я с masterа что-то потерял, тк в прошлом реквесте подобная проблема возникала.

2021-07-10 17:36 UTC, FrediKats commented
А... что значит с мастера потерял?
Энивей, код не собирается, мы его никак не сможем вмерджить.

2021-07-10 18:01 UTC, TomGnill commented
Хм, пофиксилось вроде, но вопрос ещё открыт: что с вступлениями и выводами делать при множественной генерации?

2021-07-10 18:39 UTC, annchous commented
Пожалуйста, планируй свою работу так, чтобы не приходилось прикреплять больше одной ишуи. "Чем больше "вынесешь" за один заход, тем лучше" тут не работает.

2021-07-11 13:36 UTC, FrediKats commented
>что с вступлениями и выводами делать при множественной генерации
Я тебе уже говорил, что ты можешь без них пока сделать, а потом отдельным пр реализовать, когда мы решим. @annchous правильно заметила, что не стоит в пр кидать все, чтобы мы потом не затягивали ревью на 100+ комментов =_=

2021-07-11 13:50 UTC, VitalDikov commented on Kysect.AssignmentReporter/ReportGenerator/MarkdownReportGenerator.cs
> +            if (!reportExtendedInfo.Path.EndsWith(".md"))
оператор сравнения не нужен

2021-07-11 13:52 UTC, VitalDikov commented on Kysect.AssignmentReporter/ReportGenerator/SimpleTextReportGenerator.cs
> +            }
может декомпозировать в отдельный метод

2021-07-11 13:55 UTC, VitalDikov commented on Kysect.AssignmentReporter/Models/ReportExtendedInfo.cs
> +            Conclusion = conclusion;
для этого есть (Path,  Intro, Conclusion) = (path, intro, conclusion)

2021-07-11 14:31 UTC, FrediKats requested changes

2021-07-11 14:31 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchRules/SearchSettings.cs
> +            return WhiteFileNames.Contains(fileName) || !BlackFileNames.Contains(fileName);
Почему?

2021-07-11 14:31 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchRules/SearchSettings.cs
> +                   ||
Почему?

2021-07-11 14:31 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/IReportGenerator.cs
> +    {
Кажется, в прошлом ПР тебе писали, чтобы ты смотреть, что ты комитишь.

2021-07-11 14:31 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/MultiGenerator/MultiGenerator.cs
> +        public FileSearchFilter Filter { get; set; }
А тут точно нужны сеттеры?

2021-07-11 14:31 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/MultiGenerator/MultiGenerator.cs
> +        }
Кажется, тут тоже можно апплаить фильтры. Например, довольно ожидаемо, что если это репо с лабами, то там помимо lab1, lab2 есть еще .git.

2021-07-11 14:31 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/MultiGenerator/MultiGenerator.cs
> +                        $@"{ReportsPath}/{new DirectoryInfo(repository).Name}")))
1) Лямбда сложно читаемая, кмк.
2) Я бы string.Empty бы в локальные переменные записал, чтобы было хоть понятно что это. Либо там можно явно написать лейбл с названием аргумента

2021-07-11 14:31 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/SimpleTextReportGenerator.cs
> +                builder.Append("```");
А зачем?

2021-07-11 14:31 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/SimpleTextReportGenerator.cs
> +            }
Мне не очень нравится, что в 3 местах эта проверка.

2021-07-11 14:59 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/MultiGenerator/MultiGenerator.cs
> +        }
думал над этим, но тогда там надо уже полученный список отфильтровать

2021-07-11 15:00 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/MultiGenerator/MultiGenerator.cs
> +                        $@"{ReportsPath}/{new DirectoryInfo(repository).Name}")))
насчёт второго, это заглушка по сути тк мы ещё не знаем как это вводить, и да титульник для docx я бы тогда сделал вообще дефолтным, пусть даже пустой но будет добавляться.

2021-07-11 15:01 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/SimpleTextReportGenerator.cs
> +            }
ну я могу формат в самой генерации добавить. Но это нужная вещь, тк мне нужно сформировывать путь к отчёту, а мы передаём лишь папку для того где они будут складываться. Короче или так, или вот как написал выше, можешь свой вариант предложить

2021-07-11 15:03 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/SimpleTextReportGenerator.cs
> +                builder.Append("```");
Не обратил внимание.

2021-07-11 15:03 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/MultiGenerator/MultiGenerator.cs
> +        public FileSearchFilter Filter { get; set; }
хм, в принципе нет

2021-07-11 15:04 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchRules/SearchSettings.cs
> +            return WhiteFileNames.Contains(fileName) || !BlackFileNames.Contains(fileName);
Потому что если я ничего из имён не передам, у меня никакие файлы не добавятся.

2021-07-11 15:05 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchRules/SearchSettings.cs
> +                   ||
аналогично

2021-07-13 10:59 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/ReportExtendedInfo.cs
> +            Conclusion = conclusion;
О, я не знал что так можно, спасибо

2021-07-13 11:00 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/SimpleTextReportGenerator.cs
> +            }
Тут не уверен что вообще это нужно как в случае с генерацией документа.

2021-07-13 11:16 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/MultiGenerator/MultiGenerator.cs
> +                        $@"{ReportsPath}/{new DirectoryInfo(repository).Name}")))
1.переделал в foreach. Выглядит теперь вроде понятно.
2.Ок, но будут варнинги)

2021-07-13 20:21 UTC, FrediKats commented on Kysect.AssignmentReporter/ReportGenerator/MarkdownReportGenerator.cs
> +        }
Написать экстеншен метод поверх IReportGenerator, чтобы не дублировать код.

2021-07-13 20:21 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchRules/SearchSettings.cs
> +            return WhiteFileNames.Contains(fileName) || !BlackFileNames.Contains(fileName);
Ну... Дак это проблема логики? Наверное, если нет ничего в вайт листе, то не нужно проверять на него. В текущей реализации, например, не сработает вариант, когда я укажу вайтлистом папку, а в блеклисте - подпапку этой папки. (кейс не совсем из головы, это может быть папка с проектов в котором /bin)

2021-07-13 20:22 UTC, FrediKats requested changes
В целом ок, одно замечание оставил. Но та тема с вайтлистом не ок. Заведи ишую, поправить отдельным пр.

2021-07-13 20:23 UTC, TomGnill commented on Kysect.AssignmentReporter/ReportGenerator/MarkdownReportGenerator.cs
> +        }
А вот я хотел в самом интерфейсе это сделать, да вот только версия языка в проекте не позволила!

2021-07-13 20:44 UTC, FrediKats approved these changes

2021-07-13 20:44 UTC, merged