IDE integration
kysect/AssignmentReporter pull request #21
Opened 2021-07-19 19:44 UTC by TomGnill

2021-07-21 13:14 UTC, annchous commented on Kysect.AssignmentReporter.Plugin/Windows/SearchSettingsWindow.xaml
> +        <Button Content="Стандартный фильтр(C#)" VerticalAlignment="Bottom" HorizontalAlignment="Right" Click="get_SetDefaultSearchSettings_Button_Click" Name="get_DefaultSearchSettigs_Button" Height
Просто мимо проходила, но тут мне кажется, что лучше текст сделать на английском языке. Просто ~русский не нужен~ так более универсально и раздражать не будет, если вся IDE на английском. Ну или добавить опцию выбора языка для расширения!

2021-07-21 13:41 UTC, annchous commented
Мне кажется, что к функциональности стоит добавить возможность 1) указывать ссылку на удалённый репозиторий, а не только локальный; 2) добавить возможность выставить что-то типа * эта директория *, когда пользуешься расширением, находясь в самом проекте (мб даже возможность подгрузить названия проектов в солюшене, который открыть сейчас), если это реально как-то сделать, конечно 🤔 
Но пункт 1 довольно полезен будет, кмк

cc: @FrediKats

2021-07-23 07:30 UTC, TomGnill commented on Kysect.AssignmentReporter.Plugin/Windows/SearchSettingsWindow.xaml
> +        <Button Content="Стандартный фильтр(C#)" VerticalAlignment="Bottom" HorizontalAlignment="Right" Click="get_SetDefaultSearchSettings_Button_Click" Name="get_DefaultSearchSettigs_Button" Height
В целом идея годная, но опция выбора языка это больше похоже на новую ишую) 
А то pr сам по себе довольно большой.

2021-07-30 18:58 UTC, FrediKats requested changes

2021-07-30 18:58 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/ToolWindow.cs
> +    /// </summary>
Кажется, что можно дропнуть дефолтные комменты. Они только отвлекают т.к. кажется, что они инфомративные.

2021-07-30 18:58 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/Windows/CoverPageSettingsWindow.xaml
> +    <Grid Margin="65,-150,10,0" Height="450" VerticalAlignment="Bottom">
Уф, очень много Margin (ещё и отрицательный..ю), которые прям очень больно выглядит. И кажется, что это нужно будет руками править, если нужно будет ещё что-то добавить. Кажется, что для таких вещей лучше заюзать тот же StackPanel, который сам разрулит отступы между элементами.

2021-07-30 18:58 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/Windows/SearchSettingsWindow.xaml
> +        <Button Content="Стандартный фильтр(C#)" VerticalAlignment="Bottom" HorizontalAlignment="Right" Click="get_SetDefaultSearchSettings_Button_Click" Name="get_DefaultSearchSettigs_Button" Height
Но ты же завёл ишую, да?)

2021-07-30 18:58 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/Windows/SearchSettingsWindow.xaml.cs
> +        public Kysect.AssignmentReporter.Models.FileSearchRules.SearchSettings Settings;
Зачем?

2021-07-30 18:58 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/Windows/SearchSettingsWindow.xaml.cs
> +        public ISearchSettingsBuilder Builder = new SearchSettingsBuilder();
Кажется, что настройки однотипные. Мы можем добавить возможность их сохранять в файл и загружать с него?

2021-07-30 18:58 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/Windows/SearchSettingsWindow.xaml.cs
> +                AddWhiteFiles(string_WhiteFileNames.Text.Split(',').ToList());
Можно вместо текста через запятую сделать ListView (или ListBox, не помню как он там), чтобы они наглядно отображались.
(отдельной ишуей, ага)

2021-07-30 18:58 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/Windows/SearchSettingsWindow.xaml.cs
> +        }
А вот эти методы используются только 1 раз? Не очень понял зачем их выносить.

2021-07-30 18:58 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/Windows/ToolWindowControl.xaml.cs
> +        private void Generate_Button_Click(object sender, RoutedEventArgs e)
Заведи ишую на то, чтобы переписать это всё с использованием MVVM.

2021-07-30 18:58 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/Windows/ToolWindowControl.xaml.cs
> +        }
Так и задумано?

2021-07-30 18:58 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/Windows/ToolWindowControl.xaml.cs
> +                if (_generator is DocumentReportGenerator && _coverPageInfo != null)
Не очень понял.
1) У тебя всегда `_generator is DocumentReportGenerator`, т.к. `IReportGenerator _generator = new DocumentReportGenerator();`
2) Какая-то непонятная логика, ты ж _generator вообще не юзаешь. Кажется, тебе не нужно его делать полем совсем 🤔

2021-07-30 18:58 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/Windows/ToolWindowControl.xaml.cs
> +                    _generator = new DocumentReportGenerator();
Вот. Кажется, что тут не нужно создавать генератор, а достаточно просто сохранить выбранные настройки. А потом уже в одном месте по этим параметрам создавать что тебе нужно.

2021-08-01 09:41 UTC, TomGnill commented on Kysect.AssignmentReporter.Plugin/Windows/SearchSettingsWindow.xaml.cs
> +        public ISearchSettingsBuilder Builder = new SearchSettingsBuilder();
Можем, а вот вопрос, где хранить сохранённые настройки и в каком формате.

2021-08-01 09:50 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/Windows/SearchSettingsWindow.xaml.cs
> +        public ISearchSettingsBuilder Builder = new SearchSettingsBuilder();
Какой-то json конфиг, я думаю.
Только давай отдельным пул реквестом.

2021-08-01 09:56 UTC, TomGnill commented on Kysect.AssignmentReporter.Plugin/Windows/SearchSettingsWindow.xaml.cs
> +        public ISearchSettingsBuilder Builder = new SearchSettingsBuilder();
Давай тогда по порядку, что в этом pr нужно доделать, а что на следующий оставить?

2021-08-01 10:10 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/Windows/SearchSettingsWindow.xaml.cs
> +        public ISearchSettingsBuilder Builder = new SearchSettingsBuilder();
Я на остальных писал, что лучше ишую завести и отдельно делать.

2021-08-10 06:30 UTC, FrediKats approved these changes
Не забудь на те комменты ишуи завести.

2021-08-10 06:49 UTC, merged