Transition to MVVM
kysect/AssignmentReporter pull request #24
Opened 2021-08-12 18:20 UTC by TomGnill

2021-08-14 17:06 UTC, FrediKats requested changes

2021-08-14 17:06 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/ViewModel/CoverPageSettingsViewModel.cs
> +namespace Kysect.AssignmentReporter.Plugin.VIewModel
VIewModel -> ViewModel

2021-08-14 17:06 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/ViewModel/AssignmentReporterPluginCommand.cs
> +    public class AssignmentReporterPluginCommand : ICommand
Это не совсем ViewModel. Думаю, стоит вынести в отдельную папку а-ля MvvmBase или что-то такое. И я бы назвал как-то более generic т.к. это дефолтная имплементация. Как её там на метаните называют? RelayCommand?

2021-08-14 17:06 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/ViewModel/BillingGenerationsSettings/Notifier.cs
> +   public class Notifier : INotifyPropertyChanged
Это тоже в base mvvm. И кажется, это обычно называют BaseViewModel.

2021-08-14 17:06 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/ViewModel/BillingGenerationsSettings/Notifier.cs
> +       public event PropertyChangedEventHandler PropertyChanged = delegate { };
А там точно нужно то, что после равно?

2021-08-14 17:06 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/ViewModel/BillingGenerationsSettings/Notifier.cs
> +       protected void NotifyPropertyChanged(string propertyName)
Емнип, там через CallerMemberName атрибут это делается проще, но я не уверен.

2021-08-14 17:06 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/ViewModel/CoverPageSettingsViewModel.cs
> +               NotifyPropertyChanged("FullName");
Лучше писать nameof(FullName), но если через атрибуты делать, о которых выше написал, то можно вообще не писать.

2021-08-14 17:06 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/ViewModel/CoverPageSettingsViewModel.cs
> +                      (_coverPageSettings = new AssignmentReporterPluginCommand(obj =>
Я бы вынес лямду в метод, а вместо отложенной инициализации явно в конструкторе создаение команды сделать (и без поля лишнего)

2021-08-14 17:06 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/ViewModel/GeneratorSettingsViewModel.cs
> +                    IsPdf = true;
А зачем тебе это поле сетить, если ты вместо его исользования можешь вставить (`_selectedGeneratorType == ".pdf"`)?

2021-08-14 17:06 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/ViewModel/GeneratorSettingsViewModel.cs
> +                       (_selectPathToRepositoryCommand = new AssignmentReporterPluginCommand(obj =>
Аналогично - убрать поле, вынести в метод, унести в конструктор.

2021-08-14 17:06 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/ViewModel/GeneratorSettingsViewModel.cs
> +
А ты же от Notifyer наследуешься, у тебя и так есть этот метод, разве нет?

2021-08-14 17:06 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/Windows/CoverPageSettingsWindow.xaml
>          <TextBlock VerticalAlignment="Bottom" HorizontalAlignment="Left" Height="27" Width="179" Margin="58,-277,0,664"
Ты завёл таску на то, чтобы от margin перейти к адаптивной разметке?)

2021-08-14 17:17 UTC, TomGnill commented on Kysect.AssignmentReporter.Plugin/Windows/CoverPageSettingsWindow.xaml
>          <TextBlock VerticalAlignment="Bottom" HorizontalAlignment="Left" Height="27" Width="179" Margin="58,-277,0,664"
А, видимо это окошко пропустил когда фиксил

2021-08-20 16:52 UTC, TomGnill commented on Kysect.AssignmentReporter.Plugin/ViewModel/BillingGenerationsSettings/Notifier.cs
> +       public event PropertyChangedEventHandler PropertyChanged = delegate { };
Что-то мне подсказывает что решарпер бы мне сказал о бесполезности того, что идёт после =

2021-08-20 17:17 UTC, TomGnill commented on Kysect.AssignmentReporter.Plugin/ViewModel/BillingGenerationsSettings/Notifier.cs
> +       protected void NotifyPropertyChanged(string propertyName)
Через NameOf ещё ладно, но CallerMemberName мне не строку возвращает. Либо чтобы сделать то что ты хочешь нужна какая-то сборка

2021-08-20 17:20 UTC, TomGnill commented on Kysect.AssignmentReporter.Plugin/ViewModel/CoverPageSettingsViewModel.cs
> +               NotifyPropertyChanged("FullName");
NotifyPropertyChanged(nameof(CallerMemberNameAttribute)); мб так?

2021-08-22 20:56 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/ViewModel/BillingGenerationsSettings/Notifier.cs
> +       protected void NotifyPropertyChanged(string propertyName)
`void OnPropertyChanging([CallerMemberName] string propertyName = null)`

2021-08-22 20:57 UTC, FrediKats commented on Kysect.AssignmentReporter.Plugin/ViewModel/CoverPageSettingsViewModel.cs
> +               NotifyPropertyChanged("FullName");
Например, так https://rehansaeed.com/model-view-viewmodel-mvvm-part3-inotifypropertychanged/

2021-08-22 21:35 UTC, FrediKats approved these changes

2021-08-22 21:47 UTC, merged