Feat#1
kysect/AssignmentReporter pull request #9
Opened 2021-05-16 23:33 UTC by TomGnill

Добавлена возможность, добавить информацию о всех файлах находящихся в указанной директории и подпапках. Я бы немного пересмотрел структуру проекта, что бы фильтры на формат файла и название каталога применялись в SourceCodeProvider. Так же GitHubProvider по идее будет пользоваться функционалом FlieSystemCP. Могу ли я просто реализовать логику клонирования репозитория?

2021-05-17 12:49 UTC, FrediKats requested changes
1. Оставил ряд комментариев. Особенно сильно не нравится попытки вхордкодить что-то.
2. Когда ты хочешь прилинковать больше двух ишьюс - ты делаешь что-то не так. Я уже говорил, что стоит делать все иттеративно. Сейчас ты вместе с файловой системой задел гитхаб, но он не реализован в том виде, в котором ожидается и из-за этого ты не сможешь смердить реализацию обхода файлов без гитхаба. Не надо так.
3. "фильтры на формат файла и название каталога применялись в SourceCodeProvider" - это можно обсудить, но потом.
4. "Могу ли я просто реализовать логику клонирования репозитория" - нет. Там еще должна быть инкрементальная подгрузка, а в дальнейшем, возможно, работа с ветками, но это уже обсуждаемо.

2021-05-17 12:49 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileDescriptor.cs
> +            Content += $"\n{text}";
Не опять понял зачем. В какой ситуации мы не можем прочитать сразу весь файл, но можем по строкам?

2021-05-17 12:49 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        public bool IsAcceptable(string fileName, string[] formats)
Не ок. Метод должен принимать только имя файла и решать нужно ли его фильтровать. Если нужны опции - их нужно задавать через конструктор.

2021-05-17 12:49 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/FileSystemSourceCodeProvider.cs
> +        private List<FileDescriptor> getFileDescriptors(List<DirectoryInfo> infos)
Нейминг.

2021-05-17 12:49 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/FileSystemSourceCodeProvider.cs
> +            DirectoryInfo directoryInfo = new DirectoryInfo(_rootDirectoryPath);
Разве у класса Directory нет встроенного метода для обхода всех папок и файлов?

2021-05-17 12:49 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/FileSystemSourceCodeProvider.cs
> +                    }
А зачем стрим? Почему не вызвать File.ReadAll (или как там этот метод называется)?

2021-05-17 12:49 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            _localStoragePath = $@"C:\Users\{System.Environment.UserName}\AppData\Local\AssignmentReporterTmp\{_repositoryOwner}\{_repositoryName}";
Должно задаваться из-вне.

2021-05-17 12:49 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            string path = $@"C:\Users\{System.Environment.UserName}\AppData\Local\AssignmentReporterTmp";
Захардкодил строку. Не ок.

2021-05-17 12:49 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            Process.Start(@"cmd", @"/c " + $"git clone https://github.com/{_repositoryOwner}/{_repositoryName}.git {_localStoragePath}");
LibGit2Sharp умеет в `Repository.Clone($"https://github.com/{username}/{repositoryName}.git", userDirectory);`

2021-05-17 12:49 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            Thread.Sleep(5000);//переработать...
.

2021-05-17 12:49 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            return new FileSystemSourceCodeProvider(_localStoragePath).GetFiles();//считывание файлов через другой класс. Надеюсь так можно.
Комментарии в коде в таком виде не стоит оставлять.

2021-05-17 12:49 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            Process.Start(@"cmd", @"/c " + $"git clone https://github.com/{_repositoryOwner}/{_repositoryName}.git {_localStoragePath}");
А если там уже есть репозиторий? Был склонирован ранее. Кажется, его в таком случае нужно обновить, а не клонить.

2021-05-17 12:49 UTC, FrediKats commented
И нейминг пул реквеста...

2021-05-17 13:10 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            Process.Start(@"cmd", @"/c " + $"git clone https://github.com/{_repositoryOwner}/{_repositoryName}.git {_localStoragePath}");
о, я как раз сначала искал либу, потом просто команду вызвал, спасибо

2021-05-17 13:15 UTC, hrrrrustic commented on Kysect.AssignmentReporter/SourceCodeProvider/FileSystemSourceCodeProvider.cs
> +        private List<FileDescriptor> getFileDescriptors(List<DirectoryInfo> infos)
Кста это решарпер скорее всего, меня он задолбал уже этим. Он просто форсит маленькую букву при автокомплите

2021-05-17 13:24 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            return new FileSystemSourceCodeProvider(_localStoragePath).GetFiles();//считывание файлов через другой класс. Надеюсь так можно.
я себе оставил на будущее, мне просто надо было с чего-то начать

2021-05-17 15:19 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        public bool IsAcceptable(string fileName, string[] formats)
Я что-то не очень понимаю, мне нужен конструктор который будет принимать форматы файла, это будет либо запрещённые форматы, либо только разрешённые, после чего у меня будет просто приниматься имя?

2021-05-17 15:31 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/FileSystemSourceCodeProvider.cs
> +            DirectoryInfo directoryInfo = new DirectoryInfo(_rootDirectoryPath);
есть метод чтобы достать пути ко всем файлам

2021-05-17 17:45 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/FileSearchFilter.cs
> +        public bool IsAcceptable(string fileName, string[] formats)
Да (мне кажется лучше передавать поддерживаемые форматы) . Если ты хочешь запихать все в аргументы метода, то зачем тебе вообще класс и его инстансы? Пульнул бы в статику куда-нибудь глобальную и все
А так ты через конструктор конфигаешь фильтр, а потом уже просто файл ему скармливаешь

2021-05-17 17:46 UTC, hrrrrustic commented on Kysect.AssignmentReporter/SourceCodeProvider/FileSystemSourceCodeProvider.cs
> +            DirectoryInfo directoryInfo = new DirectoryInfo(_rootDirectoryPath);
```C#
var allFiles = Directory.EnumerateFiles(path, "*", SearchOption.AllDirectories);
````

2021-05-25 15:18 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/GitUserData.cs
> +        public string Password { get; set; }
В принципе можно этого избежать, если кто-то знает как мне достать данные гита, подобно тому как я это сделал с именем пользователя, буду благодарен

2021-05-25 15:20 UTC, hrrrrustic reviewed
Ты пишешь текст внутрь коммита или что?
![image](https://user-images.githubusercontent.com/35951936/119523886-d06c7180-bd85-11eb-9646-88ff41a94bb5.png)
Как это прочитать полностью?

2021-05-25 15:20 UTC, hrrrrustic commented on Kysect.AssignmentReporter/Models/GitUserData.cs
> +        }
А что с паролем?

2021-05-25 15:20 UTC, hrrrrustic commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            _localStoragePath = $@"C:\Users\{Environment.UserName}\AppData\Local\AssignmentReporterTmp\{_repositoryOwner}\{_repositoryName}";
Имхо, это все еще считается хардкодом путя

2021-05-25 15:20 UTC, hrrrrustic commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +        public async void GetRepository()
Не делай async void ради бога

2021-05-25 15:20 UTC, hrrrrustic commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +                await Task.Run(() =>  Repository.Clone(_url, _localStoragePath));
Зачем вообще здесь асинк?

2021-05-25 15:20 UTC, hrrrrustic commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +                    (_url, usernameFromUrl, types) => new UsernamePasswordCredentials());
Выглядит meh, разве нет фабрики какой-нибудь?

2021-05-25 15:20 UTC, hrrrrustic commented on Kysect.AssignmentReporter/SourceCodeProvider/ISourceCodeProvider.cs
> +using System.Threading.Tasks;
А зачем?

2021-05-25 17:43 UTC, TomGnill commented on Kysect.AssignmentReporter/Models/GitUserData.cs
> +        }
короче, надо как-то придумать доступ к приватным репо, и по сути для этого нужна авторизация, которую я в сигнатуре передам, и не оч хочется так в тупую пароли вводить) поэтому это просто временная заготовка

2021-05-25 17:46 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +                await Task.Run(() =>  Repository.Clone(_url, _localStoragePath));
да я просто тупой, забей. Уже поправил

2021-05-25 18:00 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +                    (_url, usernameFromUrl, types) => new UsernamePasswordCredentials());
тупо с документации по либе взял, там pull более красиво не сделать)

2021-05-25 18:08 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/ISourceCodeProvider.cs
> +using System.Threading.Tasks;
однажды там был тред.слип

2021-05-26 06:02 UTC, FrediKats requested changes

2021-05-26 06:02 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/GitUserData.cs
> +        public string Password { get; set; }
Я не думаю, что где-то есть метод, чтобы достать пароль) Это звучит как дыра в безопасности.

2021-05-26 06:02 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/FileSystemSourceCodeProvider.cs
> +            }
А зачем этот сплит? Через FileInfo нельзя нормально взять информацию? Не стоит руками делать парсинг стандартныз, там можно быть много но. Например, другой системные разделитель.

2021-05-26 06:02 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            _localStoragePath = $@"C:\Users\{Environment.UserName}\AppData\Local\AssignmentReporterTmp\{_repositoryOwner}\{_repositoryName}";
Плюсую.

2021-05-26 06:02 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            }
Я бы вынес в метод EnsureParentDirectoryExist, чтобы было понятно, что тут происзодит.

2021-05-26 06:02 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            string path = $@"C:\Users\{Environment.UserName}\AppData\Local\AssignmentReporterTmp";
Хардкодитшь путь.

2021-05-26 06:02 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            GetRepository();
Метод Get*, который ничего не возвращает.

2021-05-26 06:02 UTC, FrediKats commented on Kysect.AssignmentReporter/Models/GitUserData.cs
> +        public string Password { get; set; }
А через токены это не разрулить? Если можно - то через конфиг их прокидывать.

2021-05-26 06:02 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/ISourceCodeProvider.cs
> +using System.Threading.Tasks;
Поставь решарпер, включи отображение варнингов.

2021-05-26 08:15 UTC, hrrrrustic commented on Kysect.AssignmentReporter/SourceCodeProvider/ISourceCodeProvider.cs
> +using System.Threading.Tasks;
Тредслип в интерфейсе, звучит интересно!

2021-05-26 13:29 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            GetRepository();
Ну могу на download поменять, будет понятнее.

2021-05-26 13:30 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/ISourceCodeProvider.cs
> +using System.Threading.Tasks;
Да блин, не делаю я коммит из-за каждой строчки пофикшеной, я вижу что у меня подчёркнуто!

2021-05-26 14:50 UTC, hrrrrustic commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            GetRepository();
Да я как-то от download тоже что-то ожидаю в ответ

2021-05-26 15:07 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            GetRepository();
кхм, и что я могу вернуть?)

2021-05-26 23:03 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            string path = $@"C:\Users\{Environment.UserName}\AppData\Local\AssignmentReporterTmp";
я не понимаю как ещё объяснить это, у нас может быть куча репозиториев, указывать к каждому путь самостоятельно идея плохая, поэтому я просто завожу отдельную папку в которую будут сохраняться репозитории, или репозиторий, в последствии удаляться, тем более так это будет хотя бы отсортировано, и одна из ишуй будет решаться проще!

2021-05-27 00:15 UTC, TomGnill commented
Внёс некоторые правки, но хочу напомнить, некоторые идеи мне могут быть не совсем очевидны) Сам метод поиска файла чуть позже сделаю через FileInfo. Кому-то из вас (@FrediKats  или/и @hrrrrustic ) надо подумать как сделать доступ к закрытым репозиториям, потому что без непосредственного запроса с никнеймом и паролем, в этой либе вроде как вариантов других нет)

2021-05-27 08:07 UTC, hrrrrustic commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            string path = $@"C:\Users\{Environment.UserName}\AppData\Local\AssignmentReporterTmp";
Не понял проблемы

В студии ты указываешь сам дефолт папку для репозиториев. Там конечно есть по умолчанию, но у меня есть подозрения, что там хотя бы диск не хардкодится (не говоря уж о маках и линухах)
В кракене тоже самое
Даже в башовом гите нужно зайти в папку, куда будет клонится

В чем проблема здесь запросить папку или хотя бы сделать ее более независящей от платформы?

2021-05-27 14:54 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            string path = $@"C:\Users\{Environment.UserName}\AppData\Local\AssignmentReporterTmp";
> поэтому я просто завожу отдельную папку в которую будут сохраняться репозитории, или репозиторий

Ну дак вопрос как раз в том, что путь к этой папке должен задаваться при создании этого класса, а не хардкодится. Это будет рутовая папку внутри которой и будут лежать репозитории другие. Они будут лежать в rootPath\{_repositoryOwner}\{_repositoryName}. И ты все также сможешь удалением одной папки все почистить.

2021-05-27 14:59 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            string path = $@"C:\Users\{Environment.UserName}\AppData\Local\AssignmentReporterTmp";
> > поэтому я просто завожу отдельную папку в которую будут сохраняться репозитории, или репозиторий
> 
> Ну дак вопрос как раз в том, что путь к этой папке должен задаваться при создании этого класса, а не хардкодится. Это будет рутовая папку внутри которой и будут лежать репозитории другие. Они будут лежать в rootPath{_repositoryOwner}{_repositoryName}. И ты все также сможешь удалением одной папки все почистить.

Не проблема

2021-05-27 19:11 UTC, FrediKats requested changes

2021-05-27 19:11 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +        public GithubSourceCodeProvider(string owner, string name,string rootPath, GitUserData data)
Пробел)

2021-05-27 19:11 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            _localStoragePath +=$@"\{_repositoryOwner}\{_repositoryName}";
Пробел.

2021-05-27 19:11 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            EnsureParentDirectoryExist(_localStoragePath).CreateSubdirectory($"{ _repositoryOwner}\\{ _repositoryName}");
Лучше использовать Path separator

2021-05-27 19:11 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            _localStoragePath +=$@"\{_repositoryOwner}\{_repositoryName}";
И тут path separator

2021-05-27 21:21 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            _localStoragePath +=$@"\{_repositoryOwner}\{_repositoryName}";
решительно не понимаю зачем мне ';'

2021-05-28 07:54 UTC, FrediKats commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            _localStoragePath +=$@"\{_repositoryOwner}\{_repositoryName}";
Не понял откуда взялся ';'.

2021-05-28 15:29 UTC, TomGnill commented on Kysect.AssignmentReporter/SourceCodeProvider/GithubSourceCodeProvider.cs
> +            _localStoragePath +=$@"\{_repositoryOwner}\{_repositoryName}";
// The example displays the following output when run on a Windows system:
//    Path.DirectorySeparatorChar: '\'
//    Path.AltDirectorySeparatorChar: '/'
//    Path.PathSeparator: ';'
//    Path.VolumeSeparatorChar: ':'

2021-05-30 20:11 UTC, FrediKats approved these changes

2021-05-30 20:38 UTC, merged